### ISSUE TITLE
Ready for production ?

### ISSUE THREAD

**Issue by tachyons** [DannyBen/pundit_extra#2]
Hi, 
This seems an interesting project . I was about write this !! . So is this gem ready for production ? have you tried this is production applications ?

**Comment by DannyBen** [comment]
I am using it in an application that is at its final stages before going to production.
The gem itself is pretty simple, so I have sufficient confidence that it does what it says on the tin...

Take a look at the code ([view helpers](https://github.com/DannyBen/pundit_extra/blob/master/lib/pundit_extra/helpers.rb) and [autoloader](https://github.com/DannyBen/pundit_extra/blob/master/lib/pundit_extra/resource_autoload.rb) in particular) if you need to gain more confidence, and let me know if something doesnt feel right.

**Comment by tachyons** [comment]
:+1: Thanks
