### ISSUE TITLE
Pundit strong parameter mechanism

### ISSUE THREAD

**Issue by VandorpeDavid** [DannyBen/pundit_extra#6]
The load_resource uses `resource.attributes = send("#{resource_name}_params") if action == 'create'` instead of `resource.update_attributes(permitted_attributes ... ))`

https://github.com/elabs/pundit#strong-parameters

**Comment by DannyBen** [comment]
Any suggestion on how to change it so it supports both use cases? Personally, I don't remember using `permitted_attributes` in my policies.

**Comment by VandorpeDavid** [comment]
I'd use 

```
 if policy(resource).respond_to? :permitted_attributes
  resource.attributes = permitted_attributes(resource)
else
  resource.attributes = send("#{resource_name}_params")
done
```

Assuming that the existence of the permitted_attributes method on the Policy, is an indication that the developper is using this feature.

**Comment by DannyBen** [comment]
Sounds good. If you want to send a PR, that's cool, if not, I will try to make the change + tests tomorrow.

**Comment by DannyBen** [comment]
Can you check if [this PR](https://github.com/DannyBen/pundit_extra/pull/7) works for you?

``` ruby
gem 'pundit_extra', github: 'DannyBen/pundit_extra', branch: 'permitted-attributes'
```

**Comment by VandorpeDavid** [comment]
I can confirm it works for me.

Sorry for not fixing myself, I left just after my last reply.

**Comment by DannyBen** [comment]
Great. I am merging.
